#ifndef SMTPMIME_GLOBAL_H
#define SMTPMIME_GLOBAL_H

#ifdef SMTP_MIME_STATIC
#define SMTP_MIME_EXPORT
#else
#ifdef SMTP_MIME_LIBRARY
#define SMTP_MIME_EXPORT Q_DECL_EXPORT
#else
#define SMTP_MIME_EXPORT Q_DECL_IMPORT
#endif
#endif

#endif // SMTPMIME_GLOBAL_H
